language: cpp
sudo: required
compiler: 
 - gcc
before_install:
 - sudo apt-get install g++
 - sudo apt-get install build-essential
 - sudo apt-get install zlib1g-dev
 - sudo apt-get install libbz2-dev
 - sudo apt-get install libncurses5-dev
 - sudo apt-get install liblzma-dev
os:
 - linux
script: cd src && make
